# Triggers a run action on the repository of the organizer when the robot controller get modified on the main branch

name: Trigger Evaluation

on:
  push:
    branches:
      - main
    paths:
      - controllers/**

  workflow_dispatch:
    inputs:
      opponent:
        description: "Github username of opponent"
        default: ""

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send a repository dispatch event
        run: |
          curl -s -X POST -F 'organizer=ORGANIZER_USERNAME/ORGANIZER_REPOSITORY' -F'participant=${{ github.repository }}' -F'token=${{ github.token }}' -F'opponent=${{ github.event.inputs.opponent }}' https://webots.cloud/run_competition.php
